### ISSUE TITLE
filtering events table behaving strangly since last update?

### ISSUE THREAD

**Issue by stonekate** [bnicenboim/eeguana#211] opened 2022-10-07 11:08 UTC
Remember how you fixed that thing with the error longer object length is not a multiple blah blah... ? Some behaviour has now changed in a step which previously worked, where I filtered the events table.

What I want to do: to prepare for ICA, I first do `eeg_segment()` by a sentence onset and offset trigger, then to speed things up I filter only sentence segments that contain one of the target triggers:

```
  events_tbl(dat_seg) <- events_tbl(dat_seg) %>% 
    group_by(.id) %>% 
    filter(any(str_detect(.description, c("dummy","S 1","S 2","S 3","S 4","S 5","S 6"))))
```

This now gives the warning:
1: In stri_detect_regex(string, pattern, negate = negate,  ... :
  longer object length is not a multiple of shorter object length

and returns too many segments: there should be 181 target trials, but now there are 377 which is the same number as if all the practice and filler trials were still there. More concerning is that in the events table, the practice and filler triggers are no longer under .description, only target triggers, as if it has written over the filler/practice triggers?? Maybe not but I don't know what it's done.

Here's a minimal code example:

```
# load data
dat <- read_vhdr("20.vhdr")

# extract all sentences
dat_seg <- eeg_segment(dat, .description == "S195", .end = .description == "S200")
  
# extract only target sentences
events_tbl(dat_seg) <- events_tbl(dat_seg) %>% 
    group_by(.id) %>% 
    filter(any(str_detect(.description, c("S 1","S 2","S 3","S 4","S 5","S 6"))))

# should be about 181
max(dat_seg$.segments$segment)

# pre-filter: should include sentences with S 7x and S 9x triggers
unique(dat$.events$.description)

# post-filter: now S 7x and S 9x should be gone
unique(dat_seg$.events$.description)

# weirdly returns nothing
events_tbl(dat_seg) %>% filter(.description == "S 14")
dat_seg$.events %>% filter(.description == "S 14")
```

**Comment by bnicenboim** [comment] 2022-10-07 11:39
ooh, that's bad.
I'll check this on Monday (together with the other bug using `case`).

**Comment by stonekate** [comment] 2022-10-07 11:44
Thanks! I added some files to Dropbox for this specific issue: 20_prepro.rds is one I did before the last eeguana update, so it shows how the file should look (a bit downstream from the code above, but it has the expected number of segments). And then the raw files so you can run the above.

**Comment by bnicenboim** [comment] 2022-10-10 10:51
I get a warning after `eeg_segment`, was it always the case?

**Comment by stonekate** [comment] 2022-10-10 10:56
no, just checked it on a previous version of eeguana, so the warning is new

**Comment by bnicenboim** [comment] 2022-10-10 10:58
but I don't see `"S195"` or `"S200", these are triggers I see in my file 20

[1] ""          "s111"      "s130"      "s131"      "s60"      
 [6] "s61"       "s62"       "s63"       "s64"       "s132"     
[11] "s133"      "s134"      "s112"      "s121"      "s40"      
[16] "s41"       "s42"       "s43"       "s44"       "s10"      
[21] "s11"       "s12"       "s13"       "s14"       "s20"      
[26] "s21"       "s22"       "s23"       "s24"       "s30"      
[31] "s31"       "s32"       "s33"       "s34"       "Impedance"
[36] "s135"      "s122"      "s102"      "s4"

**Comment by stonekate** [comment] 2022-10-10 11:01
heh? I'll put in Dropbox again, something must have gone wrong (they exist in the same file I have open now!)

**Comment by bnicenboim** [comment] 2022-10-10 11:03
I'm using the raw files, not checking the rds file yet.
I'll also download it again.

**Comment by stonekate** [comment] 2022-10-10 11:04
yeah i'm looking at the vmrk file! ok it should be on dropbox now

**Comment by bnicenboim** [comment] 2022-10-10 11:06
but look:
https://zenodo.org/record/6992085/files/20.vmrk?download=1
S195" and "S200"  are not there

**Comment by bnicenboim** [comment] 2022-10-10 11:08
your file is different from the one here: https://zenodo.org/record/6992085#.Y0P8SEpBxhE
Am I working with the wrong files?

**Comment by stonekate** [comment] 2022-10-10 11:09
yes :) the zenodo files are INHIBIT, this is a different study, I've been putting the data in Dropbox/kate_eeg_data

**Comment by stonekate** [comment] 2022-10-10 11:09
sorry, could have made that more explicit

**Comment by bnicenboim** [comment] 2022-10-10 11:28
ok, the problem is with stringr it seems, not sure what was happening before, but this part is doesn't have any eeguana and it's giving a warning

```{r
df <- events_tbl(dat_seg) %>% 
  group_by(.id) %>% 
  filter(any(stringr::str_detect(.description, c("S 1","S 2","S 3","S 4","S 5","S 6"))))
```

I don't think eeguna has anything to do with it. In fact, this is the problematic part:
```r
stringr::str_detect(events_tbl(dat_seg)$.description, c("S 1","S 2","S 3","S 4","S 5","S 6")) 
```

**Comment by stonekate** [comment] 2022-10-10 11:40
good point. this line worked previously which is why I thought eeguana... but maybe it worked for the wrong reason. I'll look at it some more.

**Comment by bnicenboim** [comment] 2022-10-10 11:51
ok, closing it then

**Comment by stonekate** [comment] 2022-10-12 08:55
sorry to bug you about this again, I dealt with the warning, but I'm still ending up with more .ids in the segments table than in the events table... that seems weird, no? Or is it expected? I swear this wasn't the case before. For example:

```
# load data
dat <- read_vhdr("~/Dropbox/kate_eeg_data/20.vhdr")

# extract all sentences
dat_seg <- eeg_segment(dat, .description == "S195", .end = .description == "S200")

length(unique(dat_seg$.segments$.id)) # 377
  
# extract only target sentences
events_tbl(dat_seg) <- events_tbl(dat_seg) %>% 
    group_by(.id) %>% 
    filter(any(.description %in% c("S 10","S 20","S 30","S 40","S 50","S 60")))

length(unique(dat_seg$.events$.id)) # 186
length(unique(dat_seg$.segments$.id)) # 377

```

Is it because I'm applying the filter only to the events table? 

I'm just worried because it does seem to be filtering *something* out of the segments table (e.g. "S 70" and "S 90" no longer appear), but there still the original number of .ids (377) and I don't know what they are :(

**Comment by bnicenboim** [comment] 2022-10-12 09:31
first do this
```
df <- as.data.frame(events_tbl(dat_seg))
```
then apply all the grouping and 
and verify that the `df` looks as it should, without the events with the descriptions that you wanted to remove.
if that's the case, then I'll know that the problem is the events_tbl<-

**Comment by stonekate** [comment] 2022-10-12 09:45
yeah it looks as it should:

```
df <- as.data.frame(events_tbl(dat_seg))

df2 <- df %>% group_by(.id) %>% 
    filter(any(.description %in% c("S 10","S 20","S 30","S 40","S 50","S 60")))

length(unique(df2$.id)) # 186
print(unique(df2$.description)) # "S 70" and "S 90" are gone
```

**Comment by bnicenboim** [comment] 2022-10-12 09:46
ok, cool, I'll check it!

**Comment by stonekate** [comment] 2022-10-12 11:08
Ah. I just want to cut down on ICA time by ignoring .ids associated with practice or filler trials, so I was trying to cut the dataset down to only critical trials. So yes, identify some ids and then filter them out! Or maybe it's not a good idea anyway as the extra trials might help the ICA.

**Comment by bnicenboim** [comment] 2022-10-12 11:55
there are some other tricks, you can also downsample first. But I guess you're at 512Hz, right? downsampling by half might be too much.
yeah, not sure what can be done, and yes, it's not the best idea to throw away those samples.
You're running the thing in a server, right?

**Closed by bnicenboim** 2022-10-12 11:55 UTC

**Comment by stonekate** [comment] 2022-10-12 12:05
yeah it's already at 500 Hz. No problem, I have a good desktop I can run it on (I don't think Psych has a Ketos). Just out of curiosity, why did it work before to filter the segments table via the events table? Should it not have worked?

**Comment by bnicenboim** [comment] 2022-10-12 12:26
it didn't! that functionality would have been pretty complex (and with a lot of unclear situations), it was never there!

**Comment by stonekate** [comment] 2022-10-12 12:32
i swear to god it worked! All the datasets prior to the update had 186 segments in the segments table after this step, it only started being 377 afterwards... but anyway it's not important. This is the only preprocessing i've ever used such a step for and I'll never do it again :)
